[package]
name = "dprint-plugin-json"
description = "JSON formatter for dprint."
keywords = ["formatting", "formatter", "json", "jsonc"]
version = "0.11.0"
authors = ["David Sherret <dsherret@gmail.com>"]
license = "MIT"
edition = "2018"
homepage = "https://github.com/dprint/dprint-plugin-json"
repository = "https://github.com/dprint/dprint-plugin-json"

[lib]
crate-type = ["lib", "cdylib"]

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false
overflow-checks = false
panic = "abort"

[features]
wasm = ["serde_json", "dprint-core/wasm"]
tracing = ["dprint-core/tracing"]

[dependencies]
dprint-core = { version = "0.42.0", features = ["formatting"] }
jsonc-parser = { version = "0.17.0" }
serde = { version = "1.0.88", features = ["derive"] }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
dprint-development = "0.4.0"
debug-here = "0.2"
serde_json = { version = "1.0" }
